### PR TITLE
Add dynamic task scheduling

### PR DESCRIPTION
**Pull request by datMaffin**

### CODE REVIEW

**Comment by freifrauvonbleifrei** [comment]
Hm, just a few impressions here: 
  * `SpecificUOTLearningLoadModel` -- sounds quite confusing. Maybe `MicrocsecondsLearningLoadModel`?
  * `Task *rescheduleRemoveTask(const LevelVector& lvlVec);` -- if we get a task pointer back, is the task not yet deallocated in the list that we get it from? does it still live somewhere? where exactly?

**Comment by freifrauvonbleifrei** [comment]
Hi @datMaffin , is this still a WIP or should we inspect closely and merge?

**Comment by datMaffin** [comment]
Hi @freifrauvonbleifrei the current state is **not** WIP. 
You can inspect and merge it if no new issues are found.

**Comment by datMaffin** [comment]
*Pressed the wrong button and closed the pull request...
I am going to reopening it with this comment.*

**Comment by freifrauvonbleifrei** [comment]
seems I can't merge this straightforward, as `test_manager.cpp` was deleted on master -- @ge25duq why is that test gone?

**Comment by ge25duq** [comment]
@freifrauvonbleifrei  test_manager.cpp and test_ftolerance.cpp were merged into one single file. The tests are run with corresponding flags.

**Comment by freifrauvonbleifrei** [comment]
OK, I removed it again. @ge25duq / @obersteiner is it intended the boost test are not compiled and run in travis?

**Comment by ge25duq** [comment]
@freifrauvonbleifrei I disabled tests when I was installing Travis to reduce compilation time. No other specific reason. They can be enabled again in compile.sh

**Pull request merged**
