### PR TITLE
Extend README

### PR DESCRIPTION
**Pull request by freifrauvonbleifrei**
... with images taken from my dissertation ;)

### CODE REVIEW

**Comment by freifrauvonbleifrei** [comment]
@vancraar would you mind reviewing? my main concern is that figures will not be displayed properly. It's working in my browser so far ;)

**Comment by vancraar** [comment]
Images are displayed well, but the question is whether you need a white background in dark mode. Black axis labeling on a gray background can be difficult to read.
image

**Comment by freifrauvonbleifrei** [comment]
fair point, this is quite illegible. will fix!

**Comment by freifrauvonbleifrei** [comment]
Should be better now? also, the measurement graphs look quite cool in dark mode ;)

**Review by vancraar — APPROVED** [review]
Now it looks much better.

**Pull request merged**
